### ISSUE TITLE
Is Pudge still active?

### ISSUE THREAD

**Issue by lonnietc** [recoilme/pudge#15]
Hello,

I am looking for a very fast replacement for boltdb and similar that can be put into Cayley Graph DB as a new backend.

I came across your Pudge, Sniper, and B52 repos but am trying to get an idea as to which is better for my needs.

One question about Pudge is that I think I read that it does not reduce the file size when KV deletions occur unless there is a backup done.  If so, will this be fixed in the future to allow for file size reductions during use?

As I am working towards a rebirth of a graph database, there could be the need to handle dynamically adding/editing/deleting hundreds of millions of graph nodes and thus KV entries so I am looking for the fastest possible KV library that might help to make this an efficient system.

Any thoughts would be greatly appreciated.

**Comment by recoilme** [comment]
Right now sniper is good if you don't needed ordered results.

Pudge is very naive (my first attempt to db engine). It will be slow on ordering

I have plans to design boltdb compatible alternative. And start from adaptive radix tree:
https://github.com/recoilme/art

But i don't have any sponsor or something and now it's on freeze. Because i working on other project (for money)

**Comment by lonnietc** [comment]
Thanks for your comments on Pudge and I have commented in the Sniper thread on some plans as well.

I will be adding a number of features to the project that is being done and (hopefully) if all goes well then maybe I can sponsor more of your Pudge work going forward at some point. Let's see how this initial development goes.

**Comment by recoilme** [comment]
it's sounds interesting, feel free to ask me. I close this issue for now then, but i'm open for questions
